//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBazaar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OnlineBazaarResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OnlineBazaarResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineBazaar.Resources.OnlineBazaarResources", typeof(OnlineBazaarResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string CatalogText {
            get {
                return ResourceManager.GetString("CatalogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesText {
            get {
                return ResourceManager.GetString("CategoriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesTitle {
            get {
                return ResourceManager.GetString("CategoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CategoryCreateViewBtn {
            get {
                return ResourceManager.GetString("CategoryCreateViewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CategoryDesc {
            get {
                return ResourceManager.GetString("CategoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CategoryDescriptionField {
            get {
                return ResourceManager.GetString("CategoryDescriptionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display order.
        /// </summary>
        public static string CategoryDisplayOrderField {
            get {
                return ResourceManager.GetString("CategoryDisplayOrderField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string CategoryEditViewBtn {
            get {
                return ResourceManager.GetString("CategoryEditViewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CategoryNameField {
            get {
                return ResourceManager.GetString("CategoryNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string CategoryParentField {
            get {
                return ResourceManager.GetString("CategoryParentField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while creating category! Please try again..
        /// </summary>
        public static string CreateCategoryFailureMessage {
            get {
                return ResourceManager.GetString("CreateCategoryFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create category | Catalog | Online Bazaar.
        /// </summary>
        public static string CreateCategoryPageTittle {
            get {
                return ResourceManager.GetString("CreateCategoryPageTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create category.
        /// </summary>
        public static string CreateCategoryPanelTittle {
            get {
                return ResourceManager.GetString("CreateCategoryPanelTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created!.
        /// </summary>
        public static string CreateCategorySuccessMessage {
            get {
                return ResourceManager.GetString("CreateCategorySuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete parent category. Please delete childs first..
        /// </summary>
        public static string DeleteCategoryChildExistsMessage {
            get {
                return ResourceManager.GetString("DeleteCategoryChildExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while deleting this category! Please try again..
        /// </summary>
        public static string DeleteCategoryFailureMessage {
            get {
                return ResourceManager.GetString("DeleteCategoryFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted!.
        /// </summary>
        public static string DeleteCategorySuccessMessage {
            get {
                return ResourceManager.GetString("DeleteCategorySuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be greater than zero!.
        /// </summary>
        public static string DisplayOrderRangeErrorMessage {
            get {
                return ResourceManager.GetString("DisplayOrderRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display order field required!.
        /// </summary>
        public static string DisplayOrderRequiredMessage {
            get {
                return ResourceManager.GetString("DisplayOrderRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category | Catalog | Online Bazaar.
        /// </summary>
        public static string EditCategoryPageTittle {
            get {
                return ResourceManager.GetString("EditCategoryPageTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        public static string EditCategoryPanelTittle {
            get {
                return ResourceManager.GetString("EditCategoryPanelTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name field required!.
        /// </summary>
        public static string NameRequiredMessage {
            get {
                return ResourceManager.GetString("NameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category.
        /// </summary>
        public static string NewCategoryButtonText {
            get {
                return ResourceManager.GetString("NewCategoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating this category! Please try again..
        /// </summary>
        public static string UpdateCategoryFailureMessage {
            get {
                return ResourceManager.GetString("UpdateCategoryFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated!.
        /// </summary>
        public static string UpdateCategorySuccessMessage {
            get {
                return ResourceManager.GetString("UpdateCategorySuccessMessage", resourceCulture);
            }
        }
    }
}
